# **1. Problem Definition**

# **2. Data Collection**

In [ ]:
import pandas as pd
import numpy as np
import io

In [ ]:
raw_data = """EmployeeID,Age,YearsExperience,Education,Department,City,PerformanceRating,RemoteWork,Salary
1,29,3,Bachelors,Engineering,Bangalore,4,Yes,55000
2,35,8,Masters,Engineering,Pune,5,No,95000
3,41,15,PhD,Engineering,Bangalore,4,No,150000
4,,2,Bachelors,Sales,Delhi,3,Yes,42000
5,26,1,bachelors,Marketing,Mumbai,2,Yes,38000
6,38,10,Master,Sales,Delhi,4,No,88000
7,45,20,PhD,Engineering,Pune,5,No,210000
8,31,5,Bachelors,HR,Mumbai,3,Yes,50000
9,29,3,Bachelors,Engineering,Bangalore,4,Yes,55000
10,50,25,PhD,Engineering,Bangalore,,No,240000
11,23,0,High School,Sales,Delhi,2,Yes,28000
12,200,6,Masters,Marketing,Mumbai,3,No,60000
13,33,7,Bachelors,HR,Pune,4,Yes,54000
14,28,4,Bachelors,Sales,Delhi,3,Yes,45000
15,60,30,PhD,Engineering,Bangalore,5,No,9500000
16,,12,Masters,Engineering,Pune,4,No,105000
17,37,9,Masters,HR,Mumbai,3,No,72000
18,24,1,High School,Sales,Delhi,2,Yes,
19,42,16,PhD,Marketing,Bangalore,4,No,140000
20,29,3,Bachelors,Engineering,Bangalore,4,Yes,55000
21,34,8,Masters,Sales,Pune,3,No,80000
22,27,2,Bachelors,HR,Delhi,3,Yes,41000
23,39,11,Masters,Engineering,Mumbai,4,No,98000
24,46,19,PhD,Engineering,Bangalore,5,No,205000
25,32,6,Bachelors,Marketing,Pune,3,Yes,58000
"""

df = pd.read_csv(io.StringIO(raw_data))
df.head()

,EmployeeID,Age,YearsExperience,Education,Department,City,PerformanceRating,RemoteWork,Salary
0,1,29.0,3,Bachelors,Engineering,Bangalore,4.0,Yes,55000.0
1,2,35.0,8,Masters,Engineering,Pune,5.0,No,95000.0
2,3,41.0,15,PhD,Engineering,Bangalore,4.0,No,150000.0
3,4,NaN,2,Bachelors,Sales,Delhi,3.0,Yes,42000.0
4,5,26.0,1,bachelors,Marketing,Mumbai,2.0,Yes,38000.0

In [ ]:
df.tail(10)

,EmployeeID,Age,YearsExperience,Education,Department,City,PerformanceRating,RemoteWork,Salary
15,16,NaN,12,Masters,Engineering,Pune,4.0,No,105000.0
16,17,37.0,9,Masters,HR,Mumbai,3.0,No,72000.0
17,18,24.0,1,High School,Sales,Delhi,2.0,Yes,NaN
18,19,42.0,16,PhD,Marketing,Bangalore,4.0,No,140000.0
19,20,29.0,3,Bachelors,Engineering,Bangalore,4.0,Yes,55000.0
20,21,34.0,8,Masters,Sales,Pune,3.0,No,80000.0
21,22,27.0,2,Bachelors,HR,Delhi,3.0,Yes,41000.0
22,23,39.0,11,Masters,Engineering,Mumbai,4.0,No,98000.0
23,24,46.0,19,PhD,Engineering,Bangalore,5.0,No,205000.0
24,25,32.0,6,Bachelors,Marketing,Pune,3.0,Yes,58000.0

In [ ]:
df.shape

(25, 9)

In [ ]:
df.dtypes

EmployeeID             int64
Age                  float64
YearsExperience        int64
Education             object
Department            object
City                  object
PerformanceRating    float64
RemoteWork            object
Salary               float64
dtype: object

# **3. Data Cleaning**

**Detect missing values**

In [ ]:
df.isnull().sum()

EmployeeID           0
Age                  2
YearsExperience      0
Education            0
Department           0
City                 0
PerformanceRating    1
RemoteWork           0
Salary               1
dtype: int64

In [ ]:
# Droping the Salary Row becuase it is a target.
df = df.dropna(subset=["Salary"])
df.isnull().sum()

EmployeeID           0
Age                  2
YearsExperience      0
Education            0
Department           0
City                 0
PerformanceRating    1
RemoteWork           0
Salary               0
dtype: int64

*Mean is pulled toward outliers, median is not — so for skewed/outlier-prone numeric data, impute with median*

In [ ]:
median_age = df["Age"].median()
mode_prating = df["PerformanceRating"].mode()[0]
df["Age"] = df["Age"].fillna(median_age)
df["PerformanceRating"] = df["PerformanceRating"].fillna(mode_prating)

*For ordinal/discrete scales, use mode, not median or mean — because you must fill in a value that genuinely exists on that scale.*

In [ ]:
df.isnull().sum()

EmployeeID           0
Age                  0
YearsExperience      0
Education            0
Department           0
City                 0
PerformanceRating    0
RemoteWork           0
Salary               0
dtype: int64

In [ ]:
# Check duplicates while IGNORING the EmployeeID column
duplicate_check_cols = df.columns.drop('EmployeeID')

print("Number of duplicates (ignoring EmployeeID):",
      df.duplicated(subset=duplicate_check_cols).sum())

print(df[df.duplicated(subset=duplicate_check_cols, keep="first")])
# To show all duplicates (False)
# "first" show only duplicates ignore first
# "last"  show only duplicates ignore last

# Now actually remove them
df = df.drop_duplicates(subset=duplicate_check_cols)
print("Shape after removing true duplicates:", df.shape)

Number of duplicates (ignoring EmployeeID): 2
    EmployeeID   Age  YearsExperience  Education   Department       City  \
8            9  29.0                3  Bachelors  Engineering  Bangalore
19          20  29.0                3  Bachelors  Engineering  Bangalore

    PerformanceRating RemoteWork   Salary
8                 4.0        Yes  55000.0
19                4.0        Yes  55000.0
Shape after removing true duplicates: (22, 9)

In [ ]:
print(df)

    EmployeeID    Age  YearsExperience    Education   Department       City  \
0            1   29.0                3    Bachelors  Engineering  Bangalore
1            2   35.0                8      Masters  Engineering       Pune
2            3   41.0               15          PhD  Engineering  Bangalore
3            4   34.5                2    Bachelors        Sales      Delhi
4            5   26.0                1    bachelors    Marketing     Mumbai
5            6   38.0               10       Master        Sales      Delhi
6            7   45.0               20          PhD  Engineering       Pune
7            8   31.0                5    Bachelors           HR     Mumbai
9           10   50.0               25          PhD  Engineering  Bangalore
10          11   23.0                0  High School        Sales      Delhi
11          12  200.0                6      Masters    Marketing     Mumbai
12          13   33.0                7    Bachelors           HR       Pune
13          14   28.0                4    Bachelors        Sales      Delhi
14          15   60.0               30          PhD  Engineering  Bangalore
15          16   34.5               12      Masters  Engineering       Pune
16          17   37.0                9      Masters           HR     Mumbai
18          19   42.0               16          PhD    Marketing  Bangalore
20          21   34.0                8      Masters        Sales       Pune
21          22   27.0                2    Bachelors           HR      Delhi
22          23   39.0               11      Masters  Engineering     Mumbai
23          24   46.0               19          PhD  Engineering  Bangalore
24          25   32.0                6    Bachelors    Marketing       Pune

    PerformanceRating RemoteWork     Salary
0                 4.0        Yes    55000.0
1                 5.0         No    95000.0
2                 4.0         No   150000.0
3                 3.0        Yes    42000.0
4                 2.0        Yes    38000.0
5                 4.0         No    88000.0
6                 5.0         No   210000.0
7                 3.0        Yes    50000.0
9                 4.0         No   240000.0
10                2.0        Yes    28000.0
11                3.0         No    60000.0
12                4.0        Yes    54000.0
13                3.0        Yes    45000.0
14                5.0         No  9500000.0
15                4.0         No   105000.0
16                3.0         No    72000.0
18                4.0         No   140000.0
20                3.0         No    80000.0
21                3.0        Yes    41000.0
22                4.0         No    98000.0
23                5.0         No   205000.0
24                3.0        Yes    58000.0

In [ ]:
df['Education'].unique()

array(['Bachelors', 'Masters', 'PhD', 'bachelors', 'Master',
       'High School'], dtype=object)

In [ ]:
# Step 1: Standardize casing - make everything Title Case
df['Education'] = df['Education'].str.strip().str.title()
# Step 2: Check what we have now
df['Education'].unique()

array(['Bachelors', 'Masters', 'Phd', 'Master', 'High School'],
      dtype=object)

In [ ]:
# Step 3: Fix the spelling ('Master' -> 'Masters')
df['Education'] = df['Education'].replace('Master', 'Masters')

# Step 4: Final check
print(df['Education'].unique())
print(df['Education'].value_counts())
# bhej
# [REDACTED_TOKEN]

['Bachelors' 'Masters' 'Phd' 'High School']
Education
Bachelors      8
Masters        7
Phd            6
High School    1
Name: count, dtype: int64

In [ ]:
df['Age'].describe()

count     22.000000
mean      43.863636
std       35.913979
min       23.000000
25%       31.250000
50%       34.750000
75%       41.750000
max      200.000000
Name: Age, dtype: float64

In [ ]:
# Fixing Outlier

In [ ]:
# Step 1: Define a sane realistic boundary
df.loc[(df['Age'] < 18) | (df['Age'] > 65), 'Age'] = np.nan

In [ ]:
# Step 2: Recompute median AFTER removing outliers, then fill it in
median_age_clean = df['Age'].median()
df['Age'] = df['Age'].fillna(median_age_clean)

In [ ]:
df["Age"].describe()

count    22.000000
mean     36.340909
std       8.591782
min      23.000000
25%      31.250000
50%      34.500000
75%      40.500000
max      60.000000
Name: Age, dtype: float64

In [ ]:
df["Salary"].describe()

count    2.200000e+01
mean     5.206364e+05
std      2.006472e+06
min      2.800000e+04
25%      5.100000e+04
50%      7.600000e+04
75%      1.312500e+05
max      9.500000e+06
Name: Salary, dtype: float64

In [ ]:
df[['Age', 'YearsExperience', 'Education', 'Department', 'Salary']].sort_values('Salary', ascending=False).head(5)

     Age  YearsExperience Education   Department     Salary
14  60.0               30       Phd  Engineering  9500000.0
9   50.0               25       Phd  Engineering   240000.0
6   45.0               20       Phd  Engineering   210000.0
23  46.0               19       Phd  Engineering   205000.0
2   41.0               15       Phd  Engineering   150000.0

In [54]:
print("hello")

hello

In [55]:
!cd "/content/Salary-Prediction" && git save

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [56]:
!cp "/content/drive/MyDrive/Colab Notebooks/Salary_Prediction.ipynb" "/content/Salary-Prediction/" && cd "/content/Salary-Prediction" && git add Salary_Prediction.ipynb && git commit -m "Update notebook" && git push origin main

[main ebfc2e3] Update notebook
 1 file changed, 1 insertion(+), 1 deletion(-)
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 745 bytes | 745.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
remote: error: GH013: Repository rule violations found for refs/heads/main.
remote:
remote: - GITHUB PUSH PROTECTION
remote:   —————————————————————————————————————————
remote:     Resolve the following violations before pushing again
remote:
remote:     - Push cannot contain secrets
remote:
remote:
remote:      (?) Learn how to resolve a blocked push
remote:      https://docs.github.com/code-security/secret-scanning/working-with-secret-scanning-and-push-protection/working-with-push-protection-from-the-command-line#resolving-a-blocked-push
remote:
remote:
remote:       —— GitHub Personal Access Token ——————————————————————
remote:        locations:
remote:          - commit: ebfc2e30d979830fd7df9c9a4b14be4e58b44a74
remote:            path: Salary_Prediction.ipynb:1
remote:
remote:        (?) To push, remove secret from commit(s) or follow this URL to allow the secret.
remote:        https://github.com/er-prakashkumar/Salary-Prediction/security/secret-scanning/unblock-secret/3JxmwNgS1Q3yfL2aB9XFtHj1y7g
remote:
remote:
remote:
To https://github.com/er-prakashkumar/Salary-Prediction.git
 ! [remote rejected] main -> main (push declined due to repository rule violations)
error: failed to push some refs to 'https://github.com/er-prakashkumar/Salary-Prediction.git'